# Site settings
title: Towards Real Time Source Separation
tag_text: Towards Real Time Source Separation
description: A Senior Project

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed