# Site settings
title: Towards Real Time Source Separation on Edge Devices
tag_text: Towards Real Time Source Separation on Edge Devices
description: A Senior Project

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed